---
title: "Group 07 Assignment02"
author: "Shameka Brayton, Brad O'Hara"
date: "7/23/2017"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE, echo = TRUE}

setwd("~/DropBox/NYU/02_Module/08_DMR/Assignment02")
# library("rmarkdown", lib.loc="/Library/Frameworks/R.framework/Versions/3.3/Resources/library")
# install.packages('RMySQL')
# install.packages('DMwR2')
# library(DMwR2)

```


```{r workingDir ,include=FALSE}
setwd("~/DropBox/NYU/02_Module/08_DMR/Assignment02")
```

# Breast Cancer Dataset
```{r eval=TRUE, include=TRUE, echo=FALSE}
library(data.table)
mydat <- fread('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data')

names(mydat) <- c("patientID", "clump_thicknes","uniformity_cell_size","uniformity_cell_shape","marginal_adhesion","single_eipthelial","bare_nuclei","bland_chromatin","normal_nucleoli","mitoses","class")

```
This dataset is the results of examinations run on `r nrow(mydat)` patients.
```{r echo=FALSE}

```